// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Packet
{
    public static partial class Invokes
    {
        /// <summary>
        /// Use this data source to get Packet Operating System image.
        /// 
        /// &gt; This content is derived from https://github.com/terraform-providers/terraform-provider-packet/blob/master/website/docs/d/operating_system.html.markdown.
        /// </summary>
        public static Task<GetOperatingSystemResult> GetOperatingSystem(GetOperatingSystemArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetOperatingSystemResult>("packet:index/getOperatingSystem:getOperatingSystem", args ?? InvokeArgs.Empty, options.WithVersion());
    }

    public sealed class GetOperatingSystemArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// Name of the OS distribution.
        /// </summary>
        [Input("distro")]
        public string? Distro { get; set; }

        /// <summary>
        /// Name or part of the name of the distribution. Case insensitive.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        /// <summary>
        /// Plan name.
        /// </summary>
        [Input("provisionableOn")]
        public string? ProvisionableOn { get; set; }

        /// <summary>
        /// Version of the distribution
        /// </summary>
        [Input("version")]
        public string? Version { get; set; }

        public GetOperatingSystemArgs()
        {
        }
    }

    [OutputType]
    public sealed class GetOperatingSystemResult
    {
        public readonly string? Distro;
        public readonly string? Name;
        public readonly string? ProvisionableOn;
        /// <summary>
        /// Operating system slug (same as `id`)
        /// </summary>
        public readonly string Slug;
        public readonly string? Version;
        /// <summary>
        /// id is the provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetOperatingSystemResult(
            string? distro,
            string? name,
            string? provisionableOn,
            string slug,
            string? version,
            string id)
        {
            Distro = distro;
            Name = name;
            ProvisionableOn = provisionableOn;
            Slug = slug;
            Version = version;
            Id = id;
        }
    }
}
