// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Packet.Outputs
{

    [OutputType]
    public sealed class DeviceNetwork
    {
        /// <summary>
        /// IPv4 or IPv6 address string
        /// </summary>
        public readonly string? Address;
        /// <summary>
        /// CIDR suffix for IP address block to be assigned, i.e. amount of addresses.
        /// </summary>
        public readonly int? Cidr;
        /// <summary>
        /// IP version - "4" or "6"
        /// * `network_type` Network type of a device, used in [Layer 2 networking](https://www.packet.com/developers/docs/network/advanced/layer-2/). Will be one of `layer3`, `hybrid`, `layer2-individual` and `layer2-bonded`.
        /// </summary>
        public readonly int? Family;
        /// <summary>
        /// address of router
        /// </summary>
        public readonly string? Gateway;
        /// <summary>
        /// whether the address is routable from the Internet
        /// </summary>
        public readonly bool? Public;

        [OutputConstructor]
        private DeviceNetwork(
            string? address,

            int? cidr,

            int? family,

            string? gateway,

            bool? @public)
        {
            Address = address;
            Cidr = cidr;
            Family = family;
            Gateway = gateway;
            Public = @public;
        }
    }
}
