// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Packet.Outputs
{

    [OutputType]
    public sealed class GetDevicePortResult
    {
        /// <summary>
        /// Whether this port is part of a bond in bonded network setup
        /// </summary>
        public readonly bool Bonded;
        /// <summary>
        /// ID of the port
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// MAC address assigned to the port
        /// </summary>
        public readonly string Mac;
        /// <summary>
        /// Name of the port (e.g. `eth0`, or `bond0`)
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Type of the port (e.g. `NetworkPort` or `NetworkBondPort`)
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private GetDevicePortResult(
            bool bonded,

            string id,

            string mac,

            string name,

            string type)
        {
            Bonded = bonded;
            Id = id;
            Mac = mac;
            Name = name;
            Type = type;
        }
    }
}
