// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Packet.Outputs
{

    [OutputType]
    public sealed class VolumeAttachment
    {
        public readonly string? Href;

        [OutputConstructor]
        private VolumeAttachment(string? href)
        {
            Href = href;
        }
    }
}
