// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package packet

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// Provides a Packet organization datasource.
//
// > This content is derived from https://github.com/terraform-providers/terraform-provider-packet/blob/master/website/docs/d/organization.html.markdown.
func LookupOrganization(ctx *pulumi.Context, args *GetOrganizationArgs) (*GetOrganizationResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["name"] = args.Name
		inputs["organizationId"] = args.OrganizationId
	}
	outputs, err := ctx.Invoke("packet:index/getOrganization:getOrganization", inputs)
	if err != nil {
		return nil, err
	}
	return &GetOrganizationResult{
		Description: outputs["description"],
		Logo: outputs["logo"],
		Name: outputs["name"],
		OrganizationId: outputs["organizationId"],
		ProjectIds: outputs["projectIds"],
		Twitter: outputs["twitter"],
		Website: outputs["website"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getOrganization.
type GetOrganizationArgs struct {
	// The organization name
	Name interface{}
	// The UUID of the organization resource
	OrganizationId interface{}
}

// A collection of values returned by getOrganization.
type GetOrganizationResult struct {
	// Description string
	Description interface{}
	// Logo URL
	Logo interface{}
	Name interface{}
	OrganizationId interface{}
	// UUIDs of project resources which belong to this organization
	ProjectIds interface{}
	// Twitter handle
	Twitter interface{}
	// Website link
	Website interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
