// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package packet

import (
	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// Provides a resource to manage User SSH keys on your Packet user account. If you create a new device in a project, all the keys of the project's collaborators will be injected to the device.
// 
// The link between User SSH key and device is implicit. If you want to make sure that a key will be copied to a device, you must ensure that the device resource `depends_on` the key resource.
type SSHKey struct {
	s *pulumi.ResourceState
}

// NewSSHKey registers a new resource with the given unique name, arguments, and options.
func NewSSHKey(ctx *pulumi.Context,
	name string, args *SSHKeyArgs, opts ...pulumi.ResourceOpt) (*SSHKey, error) {
	if args == nil || args.Name == nil {
		return nil, errors.New("missing required argument 'Name'")
	}
	if args == nil || args.PublicKey == nil {
		return nil, errors.New("missing required argument 'PublicKey'")
	}
	inputs := make(map[string]interface{})
	if args == nil {
		inputs["name"] = nil
		inputs["publicKey"] = nil
	} else {
		inputs["name"] = args.Name
		inputs["publicKey"] = args.PublicKey
	}
	inputs["created"] = nil
	inputs["fingerprint"] = nil
	inputs["updated"] = nil
	s, err := ctx.RegisterResource("packet:index/sSHKey:SSHKey", name, true, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &SSHKey{s: s}, nil
}

// GetSSHKey gets an existing SSHKey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSSHKey(ctx *pulumi.Context,
	name string, id pulumi.ID, state *SSHKeyState, opts ...pulumi.ResourceOpt) (*SSHKey, error) {
	inputs := make(map[string]interface{})
	if state != nil {
		inputs["created"] = state.Created
		inputs["fingerprint"] = state.Fingerprint
		inputs["name"] = state.Name
		inputs["publicKey"] = state.PublicKey
		inputs["updated"] = state.Updated
	}
	s, err := ctx.ReadResource("packet:index/sSHKey:SSHKey", name, id, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &SSHKey{s: s}, nil
}

// URN is this resource's unique name assigned by Pulumi.
func (r *SSHKey) URN() *pulumi.URNOutput {
	return r.s.URN()
}

// ID is this resource's unique identifier assigned by its provider.
func (r *SSHKey) ID() *pulumi.IDOutput {
	return r.s.ID()
}

// The timestamp for when the SSH key was created
func (r *SSHKey) Created() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["created"])
}

// The fingerprint of the SSH key
func (r *SSHKey) Fingerprint() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["fingerprint"])
}

// The name of the SSH key for identification
func (r *SSHKey) Name() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["name"])
}

// The public key. If this is a file, it
// can be read using the file interpolation function
func (r *SSHKey) PublicKey() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["publicKey"])
}

// The timestamp for the last time the SSH key was updated
func (r *SSHKey) Updated() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["updated"])
}

// Input properties used for looking up and filtering SSHKey resources.
type SSHKeyState struct {
	// The timestamp for when the SSH key was created
	Created interface{}
	// The fingerprint of the SSH key
	Fingerprint interface{}
	// The name of the SSH key for identification
	Name interface{}
	// The public key. If this is a file, it
	// can be read using the file interpolation function
	PublicKey interface{}
	// The timestamp for the last time the SSH key was updated
	Updated interface{}
}

// The set of arguments for constructing a SSHKey resource.
type SSHKeyArgs struct {
	// The name of the SSH key for identification
	Name interface{}
	// The public key. If this is a file, it
	// can be read using the file interpolation function
	PublicKey interface{}
}
