// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

import {Facility} from "./index";

/**
 * Packet Connect was removed in release 2.7.0.
 *
 * > This content is derived from https://github.com/terraform-providers/terraform-provider-packet/blob/master/website/docs/r/connect.html.markdown.
 */
export class Connect extends pulumi.CustomResource {
    /**
     * Get an existing Connect resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ConnectState, opts?: pulumi.CustomResourceOptions): Connect {
        return new Connect(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'packet:index/connect:Connect';

    /**
     * Returns true if the given object is an instance of Connect.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Connect {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Connect.__pulumiType;
    }

    public readonly facility!: pulumi.Output<Facility>;
    public readonly name!: pulumi.Output<string>;
    public readonly portSpeed!: pulumi.Output<number>;
    public readonly projectId!: pulumi.Output<string>;
    public readonly providerId!: pulumi.Output<string>;
    public readonly providerPayload!: pulumi.Output<string>;
    public /*out*/ readonly status!: pulumi.Output<string>;
    public readonly vxlan!: pulumi.Output<number>;

    /**
     * Create a Connect resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ConnectArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ConnectArgs | ConnectState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as ConnectState | undefined;
            inputs["facility"] = state ? state.facility : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["portSpeed"] = state ? state.portSpeed : undefined;
            inputs["projectId"] = state ? state.projectId : undefined;
            inputs["providerId"] = state ? state.providerId : undefined;
            inputs["providerPayload"] = state ? state.providerPayload : undefined;
            inputs["status"] = state ? state.status : undefined;
            inputs["vxlan"] = state ? state.vxlan : undefined;
        } else {
            const args = argsOrState as ConnectArgs | undefined;
            if (!args || args.facility === undefined) {
                throw new Error("Missing required property 'facility'");
            }
            if (!args || args.name === undefined) {
                throw new Error("Missing required property 'name'");
            }
            if (!args || args.portSpeed === undefined) {
                throw new Error("Missing required property 'portSpeed'");
            }
            if (!args || args.projectId === undefined) {
                throw new Error("Missing required property 'projectId'");
            }
            if (!args || args.providerId === undefined) {
                throw new Error("Missing required property 'providerId'");
            }
            if (!args || args.providerPayload === undefined) {
                throw new Error("Missing required property 'providerPayload'");
            }
            if (!args || args.vxlan === undefined) {
                throw new Error("Missing required property 'vxlan'");
            }
            inputs["facility"] = args ? args.facility : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["portSpeed"] = args ? args.portSpeed : undefined;
            inputs["projectId"] = args ? args.projectId : undefined;
            inputs["providerId"] = args ? args.providerId : undefined;
            inputs["providerPayload"] = args ? args.providerPayload : undefined;
            inputs["vxlan"] = args ? args.vxlan : undefined;
            inputs["status"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(Connect.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Connect resources.
 */
export interface ConnectState {
    readonly facility?: pulumi.Input<Facility>;
    readonly name?: pulumi.Input<string>;
    readonly portSpeed?: pulumi.Input<number>;
    readonly projectId?: pulumi.Input<string>;
    readonly providerId?: pulumi.Input<string>;
    readonly providerPayload?: pulumi.Input<string>;
    readonly status?: pulumi.Input<string>;
    readonly vxlan?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a Connect resource.
 */
export interface ConnectArgs {
    readonly facility: pulumi.Input<Facility>;
    readonly name: pulumi.Input<string>;
    readonly portSpeed: pulumi.Input<number>;
    readonly projectId: pulumi.Input<string>;
    readonly providerId: pulumi.Input<string>;
    readonly providerPayload: pulumi.Input<string>;
    readonly vxlan: pulumi.Input<number>;
}
